language: node_js
node_js: node
deploy:
  provider: pages
  local_dir: dest
  target_branch: master
  skip_cleanup: true
  github_token: f6d2d0679bcbc5eaebb6d4929fcfb95dc583b808
  email: thebaronalex@gmail.com
  name: Titus Wormer
  on:
    branch: My-moves
